import type { AlgoliaSearchTranslations } from '../../types'

export const enAlgoliaSearch: AlgoliaSearchTranslations = {
  button: {
    buttonText: 'Search',
    buttonAriaLabel: 'Search'
  },
  modal: {
    searchBox: {
      clearButtonTitle: 'Clear',
      clearButtonAriaLabel: 'Clear query',
      closeButtonText: 'Close',
      closeButtonAriaLabel: 'Close',
      placeholderText: 'Search docs or ask AI',
      placeholderTextAskAi: 'Ask another question...',
      placeholderTextAskAiStreaming: 'Generating answer...',
      searchInputLabel: 'Search',
      backToKeywordSearchButtonText: 'Back to search',
      backToKeywordSearchButtonAriaLabel: 'Back to search',
      newConversationPlaceholder: 'Ask a question',
      conversationHistoryTitle: 'My conversations',
      startNewConversationText: 'Start new conversation',
      viewConversationHistoryText: 'View history',
      threadDepthErrorPlaceholder: 'Conversation limit reached'
    },
    newConversation: {
      newConversationTitle: 'How can I help you today?',
      newConversationDescription:
        'I search your documentation and help you quickly with setup guides, feature details, and troubleshooting.'
    },
    footer: {
      selectText: 'Select',
      submitQuestionText: 'Submit question',
      selectKeyAriaLabel: 'Enter',
      navigateText: 'Navigate',
      navigateUpKeyAriaLabel: 'Arrow up',
      navigateDownKeyAriaLabel: 'Arrow down',
      closeText: 'Close',
      backToSearchText: 'Back to search',
      closeKeyAriaLabel: 'Esc',
      poweredByText: 'Powered by'
    },
    errorScreen: {
      titleText: 'Unable to load results',
      helpText: 'Please check your network connection.'
    },
    startScreen: {
      recentSearchesTitle: 'Recent searches',
      noRecentSearchesText: 'No recent searches',
      saveRecentSearchButtonTitle: 'Save this search',
      removeRecentSearchButtonTitle: 'Remove this search from history',
      favoriteSearchesTitle: 'Favorites',
      removeFavoriteSearchButtonTitle: 'Remove from favorites',
      recentConversationsTitle: 'Recent conversations',
      removeRecentConversationButtonTitle: 'Remove conversation'
    },
    noResultsScreen: {
      noResultsText: 'No results',
      suggestedQueryText: 'Try searching for',
      reportMissingResultsText: 'Should this have results?',
      reportMissingResultsLinkText: 'Let us know.'
    },
    resultsScreen: {
      askAiPlaceholder: 'Ask AI:',
      noResultsAskAiPlaceholder: 'No results found? Ask AI:'
    },
    askAiScreen: {
      disclaimerText: 'This answer was generated by AI and may contain mistakes.',
      relatedSourcesText: 'Related sources',
      thinkingText: 'Thinking...',
      copyButtonText: 'Copy',
      copyButtonCopiedText: 'Copied!',
      copyButtonTitle: 'Copy',
      likeButtonTitle: 'Like',
      dislikeButtonTitle: 'Dislike',
      thanksForFeedbackText: 'Thanks for your feedback!',
      preToolCallText: 'Searching...',
      duringToolCallText: 'Searching...',
      afterToolCallText: 'Search completed',
      stoppedStreamingText: 'You stopped this answer',
      errorTitleText: 'Chat error',
      threadDepthExceededMessage: 'This conversation was ended to keep answers accurate.',
      startNewConversationButtonText: 'Start new conversation'
    }
  }
}
