import type { AlgoliaAskAiSidePanelTranslations } from '../../types'

export const enAskAiSidePanel: AlgoliaAskAiSidePanelTranslations = {
  button: {
    translations: {
      buttonText: 'Ask AI',
      buttonAriaLabel: 'Ask AI'
    }
  },
  panel: {
    translations: {
      header: {
        title: 'Ask AI',
        conversationHistoryTitle: 'My conversations',
        newConversationText: 'Start new conversation',
        viewConversationHistoryText: 'View history'
      },
      promptForm: {
        promptPlaceholderText: 'Ask a question',
        promptAnsweringText: 'Generating answer...',
        promptAskAnotherQuestionText: 'Ask another question',
        promptDisclaimerText: 'This answer was generated by AI and may contain mistakes.',
        promptLabelText: 'Press Enter to send, Shift+Enter for new line.',
        promptAriaLabelText: 'Prompt input'
      },
      conversationScreen: {
        preToolCallText: 'Searching...',
        searchingText: 'Searching...',
        toolCallResultText: 'Search completed',
        conversationDisclaimer: 'This answer was generated by AI and may contain mistakes.',
        reasoningText: 'Analyzing...',
        thinkingText: 'Thinking...',
        relatedSourcesText: 'Related sources',
        stoppedStreamingText: 'You stopped this answer',
        copyButtonText: 'Copy',
        copyButtonCopiedText: 'Copied!',
        likeButtonTitle: 'Like',
        dislikeButtonTitle: 'Dislike',
        thanksForFeedbackText: 'Thanks for your feedback!',
        errorTitleText: 'Chat error'
      },
      newConversationScreen: {
        titleText: 'How can I help you today?',
        introductionText:
          'I search your documentation and help you quickly with setup guides, feature details, and troubleshooting.'
      },
      logo: {
        poweredByText: 'Powered by'
      }
    }
  }
}
